package com.rayferric.comet.input;

public enum InputAxis {
    MOUSE_X,
    MOUSE_Y,
    MOUSE_WHEEL_X,
    MOUSE_WHEEL_Y,

    GAMEPAD_TRIGGER_LEFT,
    GAMEPAD_TRIGGER_RIGHT,
    GAMEPAD_STICK_LEFT_X,
    GAMEPAD_STICK_LEFT_Y,
    GAMEPAD_STICK_RIGHT_X,
    GAMEPAD_STICK_RIGHT_Y
}
