package com.rayferric.comet.engine;

import com.rayferric.comet.scenegraph.node.Model;
import com.rayferric.comet.scenegraph.node.Node;
import com.rayferric.comet.scenegraph.node.camera.OrthographicCamera;
import com.rayferric.comet.scenegraph.node.camera.PerspectiveCamera;
import com.rayferric.comet.scenegraph.node.light.DirectionalLight;
import com.rayferric.comet.scenegraph.node.light.PointLight;
import com.rayferric.comet.scenegraph.node.light.SpotLight;

import java.util.ArrayList;
import java.util.List;

/**
 * Layer index is a read-only structure that holds lists of different types of nodes present in a layer.<br>
 * Layer indexes are regenerated by the engine every so often and supply required node tree information to the servers.<br>
 * Layer index may be forcefully regenerated by calling {@link Layer#genIndex()}
 */
public class LayerIndex {
    /**
     * Creates a read only layer index.
     */
    public LayerIndex(Node root) {
        root.indexAll(this);
    }

    public List<Model> getModels() {
        return models;
    }

    /**
     * Adds a {@link Model} to the index.<br>
     * • Is implicitly called by the constructor when traversing the node tree.<br>
     * • Must not be called by the user, this is an internal method.<br>
     * • May be called from any thread.
     *
     * @param model the {@link Model} to be indexed
     */
    public void add(Model model) {
        models.add(model);
    }

    /**
     * Adds a {@link PerspectiveCamera} to the index.<br>
     * • Is implicitly called by the constructor when traversing the node tree.<br>
     * • Must not be called by the user, this is an internal method.<br>
     * • May be called from any thread.
     *
     * @param camera the {@link PerspectiveCamera} to be indexed
     */
    public void add(PerspectiveCamera camera) {
        perspectiveCameras.add(camera);
    }

    /**
     * Adds a {@link OrthographicCamera} to the index.<br>
     * • Is implicitly called by the constructor when traversing the node tree.<br>
     * • Must not be called by the user, this is an internal method.<br>
     * • May be called from any thread.
     *
     * @param camera the {@link OrthographicCamera} to be indexed
     */
    public void add(OrthographicCamera camera) {
        orthographicCameras.add(camera);
    }

    /**
     * Adds a {@link DirectionalLight} to the index.<br>
     * • Is implicitly called by the constructor when traversing the node tree.<br>
     * • Must not be called by the user, this is an internal method.<br>
     * • May be called from any thread.
     *
     * @param light the {@link DirectionalLight} to be indexed
     */
    public void add(DirectionalLight light) {
        directionalLights.add(light);
    }

    /**
     * Adds a {@link PointLight} to the index.<br>
     * • Is implicitly called by the constructor when traversing the node tree.<br>
     * • Must not be called by the user, this is an internal method.<br>
     * • May be called from any thread.
     *
     * @param light the {@link PointLight} to be indexed
     */
    public void add(PointLight light) {
        pointLights.add(light);
    }

    /**
     * Adds a {@link SpotLight} to the index.<br>
     * • Is implicitly called by the constructor when traversing the node tree.<br>
     * • Must not be called by the user, this is an internal method.<br>
     * • May be called from any thread.
     *
     * @param light the {@link SpotLight} to be indexed
     */
    public void add(SpotLight light) {
        spotLights.add(light);
    }

    private final List<Model> models = new ArrayList<>();
    private final List<PerspectiveCamera> perspectiveCameras = new ArrayList<>();
    private final List<OrthographicCamera> orthographicCameras = new ArrayList<>();
    private final List<DirectionalLight> directionalLights = new ArrayList<>();
    private final List<PointLight> pointLights = new ArrayList<>();
    private final List<SpotLight> spotLights = new ArrayList<>();
}
